---
- name: Register appliance
  redhat_subscription: state=present username={{ rhn_login }} password={{ rhn_password }} autosubscribe=true
  tags:
    - registrations

- name: Add sensu Repo
  copy: src=sensu.repo dest=/etc/yum.repos.d/sensu.repo owner=root group=root mode=0644
  tags:
    - repos

- name: Add Repel Repos
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm state=present
  tags:
    - repos

- name: Install nagios-plugins
  yum: name={{ item }}
  with_items:
    - sensu
    - nagios-plugins-pgsql
    - nagios-plugins-http
    - nagios-plugins-procs
  tags:
    - packages

- name: Configure Sensu server
  template: src=sensu/rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json owner=root group=root mode=0644
  tags:
    - sensu

- name: Configure Sensu client
  template: src=sensu/client.j2 dest=/etc/sensu/conf.d/client.json owner=root group=root mode=0644
  tags:
    - sensu

- name: Restart sensu-client
  service: name=sensu-client state=restarted
  tags:
    - sensu
    - restart-sensu

- name: Restart sensu-api
  service: name=sensu-api state=restarted
  tags:
    - sensu
    - restart-sensu

- name: Restart sensu-server
  service: name=sensu-server state=restarted
  tags:
    - sensu
    - restart-sensu
