heat_template_version: 2015-04-30

description: >
  Hot template to spin up a Cloudforms reference architecture on OpenStack, 1 DB, 2 WebUIs, 2 Workers.

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used
  flavor_name:
    type: string
    label: Flavor Name
    description: Name of flavor to be used
    default: m1.medium
  image_name:
    type: string
    label: Image Name
    description: Name of image to be used
    default: CloudForms 4.0 CFME 5.5.2
  public_net_name:
    type: string
    label: Public network name
    description: Name of the public network
    default: public
  private_net_name:
    type: string
    label: Private network name
    description: Name of the private network
    default: private_net
  private_subnet_name:
    type: string
    label: Private subnet name
    description: Name of the private subnet
    default: internal_subnet
  private_net_cidr:
    type: string
    label: Private Network CIDR
    description: Private network address (CIDR notation)
    default: 192.168.0.0/24
  dns_nameservers:
    type: comma_delimited_list
    description: DNS servers
    default: ["8.8.8.8","8.8.4.4"]
  source_ssh:
    type: string
    label: Source IP for SSH
    description: Authorized IP to SSH to appliance (CIDR)
    default: 0.0.0.0/0
  security_group_name:
    type: string
    label: Security Group Name
    description: Name of the default Cloudforms Security Group
    default: default_cloudforms

resources:
#Appliances
  cloudforms-db:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: cloudforms-db.yaml
        properties:
          key_name: { get_param: key_name }
          image_name: { get_param: image_name }
          flavor_name: { get_param: flavor_name }
          public_net_name: { get_param: public_net_name }
          private_net_name: { get_resource: private_net }
          private_subnet_name: { get_resource: private_subnet }
          instance_name: cloudforms-db%index%
          security_group_name: { get_param: security_group_name }
          

  cloudforms-webUI:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: cloudforms-webUI.yaml
        properties:
          key_name: { get_param: key_name }
          image_name: { get_param: image_name }
          flavor_name: { get_param: flavor_name }
          public_net_name: { get_param: public_net_name }
          private_net_name: { get_resource: private_net }
          private_subnet_name: { get_resource: private_subnet }
          instance_name: cloudforms-webUI%index%
          security_group_name: { get_param: security_group_name }

  cloudforms-wkr:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: cloudforms-wkr.yaml
        properties:
          key_name: { get_param: key_name }
          image_name: { get_param: image_name }
          flavor_name: { get_param: flavor_name }
          public_net_name: { get_param: public_net_name }
          private_net_name: { get_resource: private_net }
          private_subnet_name: { get_resource: private_subnet }
          instance_name: cloudforms-wkr%index%
          security_group_name: { get_param: security_group_name }

#Network
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      dns_nameservers:  {get_param: dns_nameservers }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_name }

  internal_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: private_subnet }
  
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Minimal Cloudforms Security Group
      name: { get_param: security_group_name }
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: { get_param: source_ssh }
